name: Docker Build Dev

on:
  push:
    branches: [ develop ]

jobs:
  build-push:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push app to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          tags: "ghcr.io/exodiafinance/exodia-frontend:development"
          push: true
          build-args: |
            GA_API_KEY=${{secrets.GA_API_KEY}}
